export const independentCities: { [stateName: string]: string[] } = {
    'VA': [
        "Alexandria",
        "Bristol",
        "Buena Vista",
        "Charlottesville",
        "Chesapeake",
        "Colonial Heights",
        "Covington",
        "Danville",
        "Emporia",
        "Fairfax",
        "Falls Church",
        "Franklin",
        "Fredericksburg",
        "Galax",
        "Hampton",
        "Harrisonburg",
        "Hopewell",
        "Lexington",
        "Lynchburg",
        "Manassas",
        "Manassas Park",
        "Martinsville",
        "Newport News",
        "Norfolk",
        "Norton",
        "Petersburg",
        "Poquoson",
        "Portsmouth",
        "Radford",
        "Richmond",
        "Roanoke",
        "Salem",
        "Staunton",
        "Suffolk",
        "Virginia Beach",
        "Waynesboro",
        "Williamsburg",
        "Winchester"
    ],
    'MO': ["St. Louis", "Saint Louis"],
    'NV': ["Carson City"],
    'MD': ["Baltimore"]
}